certificate/urls.py
from django.urls import path, include
from certificate import views

urlpatterns = [
    path('certificate/', views.certificate, name='certificate'),
    path('enrollment_letter/', views.enrollment_letter, name='enrollment_letter'),
    path('change_links/<str:next_url>', views.change_links, name='change_links'),
    path('manage_certificates/', views.manage_certificates, name='manage_certificates'),
    path('validate/', views.validate, name='validate_document')
]

education_program/urls.py
from django.urls import path
from education_program import views

urlpatterns = [
    path("insert/", views.insert_education_program, name="insert_education_program"),
    path("list/", views.list_education_programs, name="list_education_programs"),
    path("list/by_institution", views.list_institutions, name="list_education_programs_by_institution"),
    path("list/by_professor", views.list_professors, name="list_education_programs_by_professor"),
    path("<int:education_program_id>/update", views.update_education_program, name="update_education_program"),
    path("institution/<int:institution_id>/update", views.update_institution, name="update_institution"),
    path("update_all", views.update_pages, name="update_all"),
    # path("add_institution/", views.insert_institution, name='insert_institution'),
]

wikiconecta/urls.py
from django.urls import path, include
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user_profile.urls')),
    path('', include('certificate.urls')),
    path('education_program/', include('education_program.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
]

urlpatterns += staticfiles_urlpatterns()

education_program/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.core.validators import MinValueValidator
from django.conf import settings
from datetime import datetime


class Institution(models.Model):
    name = models.CharField(_("Institution or University name"), max_length=280)
    postal_code = models.CharField(_("Postal code"), max_length=20)
    state = models.CharField(_("State"), max_length=2, choices=settings.STATES, blank=True)
    city = models.CharField(_("City"), max_length=280, blank=True)
    lat = models.FloatField(_("Latitude"), null=True, blank=True)
    lon = models.FloatField(_("Longitude"), null=True, blank=True)

    def __str__(self):
        if self.city:
            return self.name + " (" + self.city + ")"
        else:
            return self.name


class Professor(models.Model):
    name = models.CharField(_("Name"), max_length=280)
    username = models.CharField(_("Wikimedia username"), max_length=280, null=True, blank=True)

    def __str__(self):
        if self.username:
            return self.name + " (" + self.username + ")"
        else:
            return self.name


class EducationProgram(models.Model):
    MODALITY = (
        ("in_person", _("In person")),
        ("hybrid", _("Hybrid")),
        ("online", _("Online")),
    )
    name = models.CharField(_("Course name"), max_length=280)
    start_date = models.DateField(_("Start date"))
    end_date = models.DateField(_("End date"))
    link = models.URLField(_("Link"), null=True, blank=True)
    course_type = models.CharField(_("Course type"), choices=MODALITY, max_length=10, default=None)
    institution = models.ManyToManyField(Institution, verbose_name=_("Institution"), related_name="education_program_institution")
    professor = models.ManyToManyField(Professor, verbose_name=_("Professor"), related_name="education_program_professor")
    number_students = models.IntegerField(_("Number of students or participants"), blank=True, null=True,
                                          validators=[MinValueValidator(0)])

    def __str__(self):
        return self.name + " (" + self.start_date.strftime("%m/%d/%Y") + "-" + self.end_date.strftime("%m/%d/%Y") + ")"

education_program/forms.py
from django import forms
from django.forms import formset_factory
from .models import EducationProgram, Professor, Institution
from django.utils.translation import gettext_lazy as _
from geopy.geocoders import Nominatim
import brazilcep
from .wiki import build_state


class EducationProgramForm(forms.ModelForm):
    class Meta:
        model = EducationProgram
        fields = ['name', 'start_date', 'end_date', 'link', 'course_type',
                  'number_students']
        widgets = {
            'course_type': forms.RadioSelect(),
            'start_date': forms.DateInput(attrs={'type': 'date', 'placeholder': 'YYYY-MM-DD'}),
            'end_date': forms.DateInput(attrs={'type': 'date', 'placeholder': 'YYYY-MM-DD'}),
            'selected_professors': forms.CheckboxSelectMultiple(attrs={'required': True})
        }


class ProfessorForm(forms.ModelForm):
    class Meta:
        model = Professor
        fields = ['name', 'username']

    def save(self, commit=True):
        name = self.cleaned_data.get('name')
        username = self.cleaned_data.get('username')

        if name and username:
            instance, created = Professor.objects.get_or_create(name=name, username=username)
        elif name:
            instance, created = Professor.objects.get_or_create(name=name)
        elif username:
            instance, created = Professor.objects.get_or_create(username=username)
        else:
            instance, created = Professor.objects.get_or_create(username="-")

        if commit:
            instance.save()

        return instance


ProfessorFormset = formset_factory(ProfessorForm, extra=1)


class InstitutionForm(forms.ModelForm):
    class Meta:
        model = Institution
        fields = ['name', 'postal_code']

    def save(self, commit=True):
        name = self.cleaned_data.get('name')
        postal_code = self.cleaned_data.get('postal_code')

        try:
            address = brazilcep.get_address_from_cep(postal_code)
            city, state = get_city_state(address)
            location = get_location_from_postal_code(f"{address['street']} - {address['city']}")
            if not location:
                location = get_location_from_postal_code(f"{address['city']}, {address['uf']}")
            lat, lon = get_coordinates(location)
        except:
            city, state, lat, lon = "", "", 0, 0

        instance, created = Institution.objects.get_or_create(name=name)

        if lat and lon:
            instance.lat = lat
            instance.lon = lon
        if city and state:
            instance.city = city
            instance.state = state
        if postal_code:
            instance.postal_code = postal_code

        if commit:
            instance.save()

        return instance


InstitutionFormset = formset_factory(InstitutionForm, extra=1)


class UpdateInstitutionForm(forms.ModelForm):
    class Meta:
        model = Institution
        fields = "__all__"

    def save(self, institution_id=None, commit=True, **kwargs):
        name = self.cleaned_data.get('name')
        postal_code = self.cleaned_data.get('postal_code')
        state = self.cleaned_data.get('state')
        city = self.cleaned_data.get('city')
        lat = self.cleaned_data.get('lat')
        lon = self.cleaned_data.get('lon')

        if institution_id:
            instance = Institution.objects.get(pk=institution_id)

            if name:
                instance.name = name
            if postal_code:
                instance.postal_code = postal_code
            if state:
                instance.state = state
            if city:
                instance.city = city
            if lat:
                instance.lat = lat
            if lon:
                instance.lon = lon

            if commit:
                instance.save()

            return instance


def get_location_from_postal_code(address):
    geolocator = Nominatim(user_agent="WikiConecta")
    location = geolocator.geocode(address, country_codes=["br"])
    return location


def get_coordinates(location):
    if location.latitude and location.longitude:
        return location.latitude, location.longitude
    else:
        return 0, 0


def get_city_state(address):
    return address["city"], address["uf"]

education_program/views.py
from django.conf import settings
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.contrib.auth.decorators import login_required, permission_required
from .forms import EducationProgramForm, ProfessorFormset, InstitutionFormset, UpdateInstitutionForm
from .models import EducationProgram, Institution, Professor
from .wiki import edit_page, build_states, build_mapframe, get_number_of_students_of_a_outreach_dashboard_program
from django.utils.translation import gettext_lazy as _


@login_required
def insert_education_program(request):
    program_form = EducationProgramForm(request.POST or None, prefix='program')
    professor_formset = ProfessorFormset(request.POST or None, prefix='professor')
    institution_formset = InstitutionFormset(request.POST or None, prefix='institution')

    if request.method == "POST":
        professors_list = []
        institutions_list = []
        if professor_formset.is_valid():
            for professor_form in professor_formset:
                if professor_form.is_valid():
                    professor = professor_form.save()
                    professors_list.append(professor.id)
        if institution_formset.is_valid():
            for institution_form in institution_formset:
                if institution_form.is_valid():
                    institution = institution_form.save()
                    institutions_list.append(institution.id)
        if program_form.is_valid():
            program = program_form.save()
            program.professor.set(list(set(professors_list)))
            program.institution.set(list(set(institutions_list)))
            if program.link.startswith("https://outreachdashboard.wmflabs.org/courses/"):
                outreach_number = get_number_of_students_of_a_outreach_dashboard_program(program.link)
                if outreach_number:
                    program.number_students = outreach_number
            program.save()

        edit_page(request, settings.LIST_PAGE, build_states(), _("Adding or editing education program"))
        edit_page(request, settings.MAP_PAGE, build_mapframe(), _("Adding or editing education program"))
        return redirect("https://pt.wikiversity.org/wiki/WikiConecta")
    else:
        return render(request, "education_program/add_education_program.html", {
            'program_form': program_form,
            'professor_formset': professor_formset,
            'institution_formset': institution_formset
        })


@permission_required("education_program.change_educationprogram")
def update_education_program(request, education_program_id):
    program = get_object_or_404(EducationProgram, id=education_program_id)

    program_form = EducationProgramForm(request.POST or None, prefix='program', instance=program)
    professor_formset = ProfessorFormset(request.POST or None, prefix='professor')
    institution_formset = InstitutionFormset(request.POST or None, prefix='institution')

    if request.method == "POST":
        professors_list = []
        institutions_list = []
        if professor_formset.is_valid():
            for professor_form in professor_formset:
                if professor_form.is_valid():
                    professor = professor_form.save()
                    professors_list.append(professor.id)
        if institution_formset.is_valid():
            for institution_form in institution_formset:
                if institution_form.is_valid():
                    institution = institution_form.save()
                    institutions_list.append(institution.id)
        if program_form.is_valid():
            program = program_form.save()
            program.professor.set(list(set(professors_list)))
            program.institution.set(list(set(institutions_list)))
            if program.link.startswith("https://outreachdashboard.wmflabs.org/courses/"):
                outreach_number = get_number_of_students_of_a_outreach_dashboard_program(program.link)
                if outreach_number:
                    program.number_students = outreach_number
            program.save()

        edit_page(request, settings.LIST_PAGE, build_states(), _("Adding or editing education program"))
        edit_page(request, settings.MAP_PAGE, build_mapframe(), _("Adding or editing education program"))
        return redirect("https://pt.wikiversity.org/wiki/WikiConecta")
    else:
        return render(request, "education_program/update_education_program.html", {
            'program_form': program_form,
            'professor_formset': professor_formset,
            'institution_formset': institution_formset
        })


def list_education_programs(request):
    education_programs = EducationProgram.objects.all()
    context = {"programs": education_programs}
    return render(request, "education_program/list_education_programs.html", context)


@permission_required("education_program.change_institution")
def update_institution(request, institution_id):
    obj = get_object_or_404(Institution, id=institution_id)

    if request.method == "POST":
        institution_form = UpdateInstitutionForm(request.POST or None)
        if institution_form.is_valid():
            institution_form.save(institution_id=institution_id)
        context = {"institution": institution_form}
        return render(request, "education_program/update_institution.html", context)
    if request.method == "GET":
        institution_form = UpdateInstitutionForm(instance=obj)
        context = {"institution": institution_form}
        return render(request, "education_program/update_institution.html", context)


def update_pages(request):
    education_programs = EducationProgram.objects.all()

    for program in education_programs:
        if program.link.startswith("https://outreachdashboard.wmflabs.org/courses/"):
            outreach_number = get_number_of_students_of_a_outreach_dashboard_program(program.link)
            if outreach_number:
                program.number_students = outreach_number
                program.save()
    edit_page(request, settings.LIST_PAGE, build_states(), _("Adding or editing education program"))
    edit_page(request, settings.MAP_PAGE, build_mapframe(), _("Adding or editing education program"))
    return redirect("https://pt.wikiversity.org/wiki/" + settings.LIST_PAGE)


def list_institutions(request):
    institutions = Institution.objects.filter(education_program_institution__institution__isnull=False).order_by("name").distinct()
    context = {"institutions": institutions}
    return render(request, "education_program/list_education_programs_by_institution.html", context)


def list_professors(request):
    professors = Professor.objects.filter(education_program_professor__isnull=False).order_by("name").distinct()
    context = {"professors": professors}
    return render(request, "education_program/list_education_programs_by_professor.html", context)


def lang_ptbr_converter(lang):
    if lang == "pt-br" or lang == "pt":
        return "pt_BR"
    else:
        return lang

templates/education_program/list_education_programs.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}

{% block title %}{% trans "Education Programs" %}{% endblock %}

{% block styles %}
    <link rel="stylesheet" href="https://tools-static.wmflabs.org/cdnjs/ajax/libs/bootstrap/5.2.3/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://tools-static.wmflabs.org/cdnjs/ajax/libs/bootstrap-table/1.21.2/bootstrap-table.min.css">
{% endblock %}

{% block content %}
    <h1>{% trans "List of education programs" %}</h1>
    <p><a href="{% url 'list_education_programs_by_institution' %}" aria-label="{% trans 'Education programs by institution' %}">{% trans "Click here to see the education programs divided by institution" %}</a></p>
    <p><a href="{% url 'list_education_programs_by_professor' %}" aria-label="{% trans 'Education programs by professor' %}">{% trans "Click here to see the education programs divided by professor" %}</a></p>
    <div class="userform">
        <div class="w3-row">
            <div class="w3-half formfield"><input id="customSearch" type="search" placeholder="{% trans 'Search' %}" aria-label="{% trans 'Search' %}" autocomplete="on" ></div>
        </div>
        <table id="education_programs" class="table table-striped table-fixed"
               data-mobile-responsive="true"
               data-check-on-init="true"
               data-filter-control="true"
               data-show-search-clear-button="true"
               data-search="true"
               data-search-selector="#customSearch">
            <thead>
                <tr>
                    <th data-field="id" data-sortable="true">{% trans "ID" %}</th>
                    <th data-field="name" data-sortable="true">{% trans "Course" %}</th>
                    <th data-field="institution" data-sortable="true">{% trans "Institution" %}</th>
                    <th data-field="professors" data-sortable="true">{% trans "Professors" %}</th>
                    <th data-field="start_date" data-sorter="datesSorter" data-sortable="true">{% trans "Start date" %}</th>
                    <th data-field="end_date" data-sorter="datesSorter" data-sortable="true">{% trans "End date" %}</th>
                    <th data-field="course_type" data-sortable="true">{% trans "Course type" %}</th>
                    <th data-field="number_students" data-sortable="true">{% trans "Number of students" %}</th>
                </tr>
            </thead>
            <tbody>
                {% for program in programs %}
                    <tr>
                        <th scope="row">{{ program.id }}</th>
                        <td>{% if program.link %}<a href="{{ program.link }}" aria-label="{{ program.name }}">{{ program.name }}</a>{% else %}{{ program.name }}{% endif %}</td>
                        <td>
                            <ul>
                                {% for institution in program.institution.all %}
                                    <li><a href="{% url 'list_education_programs_by_institution' %}#{{ institution.id }}" aria-label="{{ institution.name }}">{{ institution.name }}</a></li>
                                {% endfor %}
                            </ul>
                        </td>
                        <td>
                            <ul>
                                {% for professor in program.professor.all %}
                                    <li><a href="{% url 'list_education_programs_by_professor' %}#{{ professor.id }}" aria-label="{{ professor.name }}">{{ professor.name }}</a></li>
                                {% endfor %}
                            </ul>
                        </td>
                        <td>{{ program.start_date|date:'Y-m-d' }}</td>
                        <td>{{ program.end_date|date:'Y-m-d' }}</td>
                        <td>{{ program.course_type }}</td>
                        <td>{{ program.number_students }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}
{% block scripts %}
    <script src="https://tools-static.wmflabs.org/cdnjs/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    <script src="https://tools-static.wmflabs.org/cdnjs/ajax/libs/popper.js/2.11.6/umd/popper.js"></script>
    <script src="https://tools-static.wmflabs.org/cdnjs/ajax/libs/bootstrap/5.2.3/js/bootstrap.min.js"></script>
    <script src="https://tools-static.wmflabs.org/cdnjs/ajax/libs/bootstrap-table/1.21.2/bootstrap-table.min.js"></script>
    <script src="https://tools-static.wmflabs.org/cdnjs/ajax/libs/bootstrap-table/1.21.2/extensions/mobile/bootstrap-table-mobile.min.js"></script>
    <script src="https://tools-static.wmflabs.org/cdnjs/ajax/libs/bootstrap-table/1.21.2/extensions/filter-control/bootstrap-table-filter-control.min.js"></script>
    <script>
        $(function () {
            $('#education_programs').bootstrapTable();
        })

        function datesSorter(a, b) {
            if (new Date(a) < new Date(b)) return 1;
            if (new Date(a) > new Date(b)) return -1;
            return 0;
        }

        $(function () {
            $('[class*="bootstrap-table-filter-control-"]').wrap("<label style='width: 100%'></label>");
        })
    </script>
{% endblock %}

templates/education_program/update_institution.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}

{% block title %}{% trans "Update an Institution" %}{% endblock %}

{% block content %}
    <div class="w3-container">
        <div class="w3-row">
            <div class="w3-quarter invisible">&nbsp;</div>
            <div class="w3-half"><h1>{% trans "Update an Institution" %}</h1></div>
            <div class="w3-quarter invisible">&nbsp;</div>
        </div>
        <div class="w3-row">
            <div class="w3-quarter invisible">&nbsp;</div>
            <div class="w3-half">{% trans "To update an Institution, fill the fields below" %}</div>
            <div class="w3-quarter invisible">&nbsp;</div>
        </div>
        <div class="w3-row">
            <div class="w3-quarter invisible">&nbsp;</div>
            <div class="w3-half">
                <form method="post" class="custom_form_large">
                    <div class="w3-container" style="display: flex; flex-direction: row; flex:1; gap:1em; justify-content: space-between; flex-wrap: wrap;">
                        {% csrf_token %}
                        <div class="w3-container" style="display: flex; flex-direction: column; flex:1; ">
                            <label for="id_name">{% trans "Institution or University name" %}:</label>
                            <input type="text" name="name" maxlength="280" id="id_name" value="{{ institution.instance.name }}">
                            <label for="id_postal_code">{% trans "Postal code" %}:</label>
                            <input type="text" name="postal_code" maxlength="20" id="id_postal_code" value="{{ institution.instance.postal_code }}">
                            <label for="id_state">{% trans "State" %}:</label>
                            <select name="state" id="id_state" required>
                                <option value="">---------</option>
                                <option value="AC" {% if institution.instance.state == "AC" %}selected{% endif %}>{% trans "Acre" %}</option>
                                <option value="AL" {% if institution.instance.state == "AL" %}selected{% endif %}>{% trans "Alagoas" %}</option>
                                <option value="AM" {% if institution.instance.state == "AM" %}selected{% endif %}>{% trans "Amazonas" %}</option>
                                <option value="AP" {% if institution.instance.state == "AP" %}selected{% endif %}>{% trans "Amapá" %}</option>
                                <option value="BA" {% if institution.instance.state == "BA" %}selected{% endif %}>{% trans "Bahia" %}</option>
                                <option value="CE" {% if institution.instance.state == "CE" %}selected{% endif %}>{% trans "Ceará" %}</option>
                                <option value="DF" {% if institution.instance.state == "DF" %}selected{% endif %}>{% trans "Distrito Federal" %}</option>
                                <option value="ES" {% if institution.instance.state == "ES" %}selected{% endif %}>{% trans "Espírito Santo" %}</option>
                                <option value="GO" {% if institution.instance.state == "GO" %}selected{% endif %}>{% trans "Goiás" %}</option>
                                <option value="MA" {% if institution.instance.state == "MA" %}selected{% endif %}>{% trans "Maranhão" %}</option>
                                <option value="MG" {% if institution.instance.state == "MG" %}selected{% endif %}>{% trans "Minas Gerais" %}</option>
                                <option value="MS" {% if institution.instance.state == "MS" %}selected{% endif %}>{% trans "Mato Grosso do Sul" %}</option>
                                <option value="MT" {% if institution.instance.state == "MT" %}selected{% endif %}>{% trans "Mato Grosso" %}</option>
                                <option value="PA" {% if institution.instance.state == "PA" %}selected{% endif %}>{% trans "Pará" %}</option>
                                <option value="PB" {% if institution.instance.state == "PB" %}selected{% endif %}>{% trans "Paraíba" %}</option>
                                <option value="PE" {% if institution.instance.state == "PE" %}selected{% endif %}>{% trans "Pernambuco" %}</option>
                                <option value="PI" {% if institution.instance.state == "PI" %}selected{% endif %}>{% trans "Piauí" %}</option>
                                <option value="PR" {% if institution.instance.state == "PR" %}selected{% endif %}>{% trans "Paraná" %}</option>
                                <option value="RJ" {% if institution.instance.state == "RJ" %}selected{% endif %}>{% trans "Rio de Janeiro" %}</option>
                                <option value="RN" {% if institution.instance.state == "RN" %}selected{% endif %}>{% trans "Rio Grande do Norte" %}</option>
                                <option value="RO" {% if institution.instance.state == "RO" %}selected{% endif %}>{% trans "Rondônia" %}</option>
                                <option value="RR" {% if institution.instance.state == "RR" %}selected{% endif %}>{% trans "Roraima" %}</option>
                                <option value="RS" {% if institution.instance.state == "RS" %}selected{% endif %}>{% trans "Rio Grande do Sul" %}</option>
                                <option value="SC" {% if institution.instance.state == "SC" %}selected{% endif %}>{% trans "Santa Catarina" %}</option>
                                <option value="SE" {% if institution.instance.state == "SE" %}selected{% endif %}>{% trans "Sergipe" %}</option>
                                <option value="SP" {% if institution.instance.state == "SP" %}selected{% endif %}>{% trans "São Paulo" %}</option>
                                <option value="TO" {% if institution.instance.state == "TO" %}selected{% endif %}>{% trans "Tocantins" %}</option>
                                <option value="XX" {% if institution.instance.state == "XX" %}selected{% endif %}>{% trans "Other" %}</option>
                            </select>
                            <label for="id_city">{% trans "City" %}:</label>
                            <input type="text" name="city" maxlength="280" id="id_city" value="{{ institution.instance.city }}">
                            <label for="id_lat">{% trans "Latitude" %}:</label>
                            <input type="number" name="lat" id="id_lat" step="any" value="{{ institution.instance.lat|floatformat:",-100" }}">
                            <label for="id_lon">{% trans "Longitude" %}:</label>
                            <input type="number" name="lon" id="id_lon" step="any" value="{{ institution.instance.lon|floatformat:",-100" }}">
                        </div>
                    </div>
                    <input class="custom_button_submitt" type="submit" value="{% trans 'Update' %}">
                </form>
                <div id="empty_form" style="display:none">{{ professor_formset.empty_form }}</div>
            </div>
            <div class="w3-quarter invisible">&nbsp;</div>
        </div>
    </div>
{% endblock %}